# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'HelloWorld' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HelloWorld
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'ART',
  'Core',
  'CxxBridge',
  'DevSupport',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTBlob',
  'RCTCameraRoll',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTPushNotification',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket',
  ]
  
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'react-native-splash-screen', :podspec => '../node_modules/react-native-mc-splash-screen/react-native-splash-screen.podspec'
  pod 'Picker', :path => '../node_modules/react-native-picker'
  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'RNZipArchive', :path => '../node_modules/react-native-mc-zip-archive', :subspecs => [
          'Core',
          'RNZASSZipArchive'
  ]
  pod 'RNFS', :path => '../node_modules/react-native-fs'

  ### 开始引入三方
  pod 'UMCCommon', '~>1.5.2'
  pod 'UMCAnalytics','~>5.5.0'
end
